"""Lint gate: every relative link and in-repo anchor in the shipped docs resolves.

Path resolution only -- this never makes a network call, so it says nothing
about `https://` links. What it does check, for every `README.md` and
`docs/**/*.md` link that is *not* an external URL:

1. The target path exists, resolved relative to the linking file's own
   directory (the way every Markdown renderer, including GitHub's, resolves
   a relative link).
2. The target does not resolve outside the repository root. `../CLAUDE.md`
   from `README.md` resolves inside this workspace, where a sibling
   `../.context/` checkout happens to sit next to `contextplane/` -- and fails on
   any standalone clone, where nothing is there. A link that only works
   because of what happens to be next to this checkout is exactly the kind of
   thing a path-resolution gate exists to catch; the workspace layout is not
   part of the contract this repository ships.
3. If the target carries a `#fragment` and resolves to a Markdown file, the
   fragment matches one of that file's heading anchors -- computed with
   GitHub's own heading-to-slug algorithm (lowercase, strip everything but
   letters/digits/spaces/hyphens/underscores, spaces become hyphens, and a
   repeated slug gets `-1`, `-2`, ... appended), so a link generated by
   copy-pasting a GitHub URL and a link into this repository's own docs are
   checked the same way.
4. A bare `#fragment` link (no path) is checked against the *linking* file's
   own headings.

What is deliberately not checked: external links (`http(s)://`, `mailto:`,
any other URL scheme), and anything reference-style (`[text][ref]` +
`[ref]: target` elsewhere in the file) -- every link in this repository's docs
is written inline, and adding reference-link resolution would mean carrying a
Markdown parser for a form nothing here uses. If that changes, this gate
needs to grow with it rather than silently miss the new form.

A line ending in `<!-- doc-link: intentional -->` is skipped entirely --
for the rare case where a link is deliberately checkout-relative-but-absent
(a generated file not present in a fresh clone, say) and the alternative is
weakening the gate for everyone.

Run locally:
    python scripts/check_doc_links.py
    python scripts/check_doc_links.py --explain
    python scripts/check_doc_links.py --paths docs/06-operations
"""

from __future__ import annotations

import argparse
import dataclasses
import re
import sys
from pathlib import Path

from checklib import repo_root, require_nonempty, run_guard

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_REPO_ROOT = repo_root()

_DEFAULT_SCOPE: tuple[str, ...] = ("README.md", "docs")

_EXCLUDE_DIRS: frozenset[str] = frozenset(
    {".venv", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "node_modules", ".git"}
)

_BYPASS_MARKER = "<!-- doc-link: intentional -->"

# `![alt](target)` and `[text](target)` both count -- an image link resolves
# the same way a regular one does, and nothing here distinguishes the two.
_LINK_RE = re.compile(r"!?\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")

# Any URL scheme (`http:`, `https:`, `mailto:`, ...) -- never resolved, never
# fetched. A relative path never contains a `:` before its first `/` on this
# platform, so this cannot misclassify a real repo-relative link.
_EXTERNAL_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.\-]*:")

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*$")
_FENCE_RE = re.compile(r"^\s*```")


# ---------------------------------------------------------------------------
# GitHub-slug anchor computation
# ---------------------------------------------------------------------------


def _strip_markdown_inline(text: str) -> str:
    """Reduce a heading line to the text GitHub slugifies.

    Inline code and links contribute their *content*, not their markup;
    `**bold**` contributes its content too. Underscores are left alone --
    they're common inside identifiers (`LOG_FORMAT`), and CommonMark itself
    does not treat an underscore as emphasis unless it sits at a word
    boundary, so stripping bare underscores would corrupt exactly the
    headings that quote a snake_case name.
    """
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\*+", "", text)
    return text


def slugify(heading: str) -> str:
    """GitHub's heading-to-anchor algorithm: lowercase, drop anything that
    isn't a letter, digit, space, hyphen, or underscore, then turn each
    remaining space into a hyphen (not collapsed -- two adjacent spaces
    left behind by a removed character become a double hyphen, which is
    the real, observable GitHub behaviour for a heading like "Cache +
    stale-on-failure")."""
    lowered = _strip_markdown_inline(heading).strip().lower()
    kept = [ch for ch in lowered if ch.isalnum() or ch in (" ", "-", "_")]
    return "".join(kept).replace(" ", "-")


def headings_of(text: str) -> list[str]:
    """Every ATX heading (`#` .. `######`) outside a fenced code block."""
    headings: list[str] = []
    in_fence = False
    for line in text.splitlines():
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = _HEADING_RE.match(line)
        if m:
            headings.append(m.group(2))
    return headings


def anchor_slugs(text: str) -> frozenset[str]:
    """Every anchor GitHub would generate for this document's headings, with
    the same disambiguating `-1`, `-2`, ... suffix GitHub appends to a
    repeated slug (second occurrence, third, ...)."""
    seen: dict[str, int] = {}
    slugs: set[str] = set()
    for heading in headings_of(text):
        base = slugify(heading)
        count = seen.get(base, 0)
        slugs.add(base if count == 0 else f"{base}-{count}")
        seen[base] = count + 1
    return frozenset(slugs)


# ---------------------------------------------------------------------------
# Scanner
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class Violation:
    """One link that does not resolve, and why."""

    path: str
    line: int
    target: str
    reason: str


def _bypassed_lines(text: str) -> frozenset[int]:
    return frozenset(i for i, line in enumerate(text.splitlines(), start=1) if _BYPASS_MARKER in line)


def check_file(path: Path, *, rel: str, repo_root: Path) -> list[Violation]:
    """Every unresolved link in *path*. Anchor checks against another file
    read that file fresh -- these docs are small enough that re-reading a
    target a second or third time costs nothing worth caching for.

    *repo_root* is resolved here rather than trusted from the caller: on
    macOS, `/tmp` (and pytest's own `tmp_path`) is a symlink to `/private/tmp`,
    so comparing an unresolved root against a `.resolve()`d link target would
    misreport every in-tree link in a temp-dir test as escaping the root.
    """
    repo_root = repo_root.resolve()
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return []

    lines = text.splitlines()
    bypassed = _bypassed_lines(text)
    own_slugs: frozenset[str] | None = None
    violations: list[Violation] = []

    for line_no, line in enumerate(lines, start=1):
        if line_no in bypassed:
            continue
        for m in _LINK_RE.finditer(line):
            target = m.group(2).strip()
            if not target or _EXTERNAL_RE.match(target):
                continue

            if target.startswith("#"):
                fragment = target[1:]
                if not fragment:
                    continue
                if own_slugs is None:
                    own_slugs = anchor_slugs(text)
                if fragment not in own_slugs:
                    violations.append(
                        Violation(rel, line_no, target, f"no heading in this file slugifies to '#{fragment}'")
                    )
                continue

            path_part, _, fragment = target.partition("#")
            resolved = (path.parent / path_part).resolve()

            try:
                resolved.relative_to(repo_root)
            except ValueError:
                violations.append(
                    Violation(
                        rel,
                        line_no,
                        target,
                        f"resolves outside the repository root ({resolved}) -- absent from a standalone clone",
                    )
                )
                continue

            if not resolved.exists():
                violations.append(Violation(rel, line_no, target, f"no file or directory at {path_part}"))
                continue

            if fragment and resolved.is_file() and resolved.suffix == ".md":
                target_text = resolved.read_text(encoding="utf-8")
                if fragment not in anchor_slugs(target_text):
                    target_rel = resolved.relative_to(repo_root)
                    violations.append(
                        Violation(rel, line_no, target, f"no heading in {target_rel} slugifies to '#{fragment}'")
                    )

    return violations


def resolve_targets(scope: list[str], *, repo_root: Path) -> list[Path]:
    out: list[Path] = []
    for entry in scope:
        target = (repo_root / entry).resolve()
        if not target.exists():
            continue
        if target.is_file():
            if target.suffix == ".md":
                out.append(target)
            continue
        for path in sorted(target.rglob("*.md")):
            if path.is_file() and not any(part in _EXCLUDE_DIRS for part in path.parts):
                out.append(path)
    return out


def _print_explain() -> int:
    print("doc-links gate: what it checks and how to clear a hit.\n")
    print("For every link in README.md and docs/**/*.md that is not an external URL:")
    print("  1. The target must exist, resolved relative to the linking file.")
    print("  2. The target must resolve inside the repository root -- a link that")
    print("     only works because of a sibling checkout in this workspace is the")
    print("     exact failure this gate exists to catch.")
    print("  3. A '#fragment' must match a real heading anchor in the target file")
    print("     (or the current file, for a bare '#fragment' link), computed with")
    print("     GitHub's own heading-to-slug algorithm.")
    print("\nNot checked: http(s)/mailto/other external URLs (no network calls), and")
    print("reference-style links (nothing in this repository's docs uses that form).")
    print(f"\nA one-off false positive may carry `{_BYPASS_MARKER}` on its own line.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Verify every relative link and anchor in README.md and docs/**/*.md resolves.",
    )
    parser.add_argument(
        "--paths",
        nargs="+",
        default=list(_DEFAULT_SCOPE),
        help="Repo-relative paths to scan (default: README.md and docs/).",
    )
    parser.add_argument("--explain", action="store_true", help="Print the rule and how to clear a hit.")
    args = parser.parse_args(argv)

    if args.explain:
        return _print_explain()

    missing = [entry for entry in args.paths if not (_REPO_ROOT / entry).exists()]
    if missing:
        print(
            f"scope does not exist under {_REPO_ROOT}: {', '.join(missing)}\n"
            "Nothing was checked, so this is a failure rather than a pass.",
            file=sys.stderr,
        )
        return 1

    targets = resolve_targets(args.paths, repo_root=_REPO_ROOT)
    # An explicit narrow --paths that holds no matching file is a fair question
    # with the answer "nothing there". A *default* scope that resolves to
    # nothing means this gate governed no file, which is a failure, not a pass.
    require_nonempty(
        targets,
        "the .md scan population (paths: " + ", ".join(args.paths) + ")",
        allow_empty=args.paths != list(_DEFAULT_SCOPE),
    )
    if not targets:
        print("nothing to scan in " + ", ".join(args.paths), file=sys.stderr)
        return 0

    violations: list[Violation] = []
    for path in targets:
        violations.extend(check_file(path, rel=str(path.relative_to(_REPO_ROOT)), repo_root=_REPO_ROOT))

    if not violations:
        print(f"doc-links gate: {len(targets)} file(s) scanned, every link resolves")
        return 0

    for v in violations:
        print(f"{v.path}:{v.line}: {v.target!r} -- {v.reason}")

    print(
        f"\n{len(violations)} broken link(s) found. Run with --explain for what this gate checks.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(run_guard(main))
