"""OperationalChainService: the signed, hash-chained record of a revision's
*operational* lifecycle -- freshness basis, legal hold, retention floor --
and the append that makes every transition provable after the fact rather
than merely stored.

Mirrors `receipt.py`'s own chain (`arc_receipt_events`/`arc_receipt_event_
heads`) in shape -- a locked head row makes append O(1), a genesis event at
sequence 0 has no predecessor, every later event's digest covers its
predecessor's -- but this is a *second*, independent chain keyed by
`revision_id`, not `receipt_id`. A revision's operational chain outlives
any one resolution and is the thing every later resolution's mandatory-
serving check will eventually have to trust (wiring that trust in is
`registry.arc.service.integrity`'s job, not this module's -- see the
class docstring below).

**Every append writes three rows in the caller's own transaction: the
event, the advanced head, and a pending checkpoint outbox row.** The
database transaction that writes the event also writes the head and the
pending checkpoint -- never one without the other two. Nothing here opens
a session -- `append_event` takes the caller's own session so the
operational write commits atomically with whatever domain change it is
evidence of (a submitted proposal's genesis event alongside its draft
revision, a source revocation's cascade alongside the source-status flip
it is evidence of).

**Signing.** Every event's raw digest is signed under a domain-separated
tag, the same shape a deployment's receipt-signing key already uses for
its own purpose. This module does not reach into `signing.py`'s
`ReceiptSigningProvider`, because every purpose that provider serves is
gated behind operator-configured key material this deployment does not
have yet (`services.py`'s own `arc_signing_keys = {}`) -- reusing that gate
here would mean this service, and therefore `SourceStatusService`'s
revocation/expiry cascade injected on top of it, could never actually
append anything on any deployment that exists today. Instead this module
generates its own Ed25519 keypair once per process (`_process_signing_key`,
cached) and signs with it directly. Private key material never leaves
process memory and is never persisted to any table -- but it also does not
survive a restart or scale past one process, which is a real production
gap, not a hidden one: a deployment that needs rotation, multi-process
consistency, or HSM/KMS custody for this signature needs the same kind of
operator-configured key material every other ARC signing purpose is
already waiting on, and wiring that in is a follow-up, not something this
task invents a shape for. `_register_public_key` keeps every key this
process has ever signed with (not just the current one) resolvable by
`verify_chain`, so a key generated by one wiring call site
(`wiring/services.py`) can still verify a chain another call site
(`wiring/jobs.py`) extended -- see both modules' own comments for why two
call sites exist at all.
"""

from __future__ import annotations

import dataclasses
import datetime
import functools
import hashlib
import json
import uuid
from collections.abc import Mapping
from typing import Any

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from registry.arc.schemas.authoring_profile_shapes import OPERATIONAL_EVENT_PROFILE
from registry.arc.schemas.authoring_profiles import canonicalize_operational_event_v1
from registry.arc.service.queries import operational_chain as queries
from registry.arc.service.queries.operational_chain import ExistingEvent
from registry.exceptions import RegistryError
from registry.types import Clock

# The closed five-literal event vocabulary this chain is allowed to carry.
EVENT_INITIALIZED = "operational_state_initialized"
EVENT_FRESHNESS_DOWNGRADED = "freshness_downgraded"
EVENT_LEGAL_HOLD_PLACED = "legal_hold_placed"
EVENT_LEGAL_HOLD_RELEASED = "legal_hold_released"
EVENT_RETENTION_EXTENDED = "retention_extended"

ACTOR_ROLE_SYSTEM = "system"
ACTOR_ROLE_HUMAN = "human"

# The exact system principal every genesis event is authored by:
# {issuer='registry://deployment', subject='arc-operational-state',
# role='system'}.
SYSTEM_ACTOR_ISSUER = "registry://deployment"
SYSTEM_ACTOR_SUBJECT = "arc-operational-state"

#: Domain-separation prefix the raw digest is signed under. Distinct from
#: `SIGNATURE_PROFILE` below: the profile is what a verifier is told to
#: look for on the row, the prefix is what actually goes into the signed
#: bytes.
_SIGNATURE_DOMAIN = b"ARC-OPERATIONAL-EVENT-V1\x00"
SIGNATURE_PROFILE = "arc_operational_event_sig_v1"

#: Every deployment's process-generated key uses this id. Stable and
#: descriptive rather than random, because it is the value every event this
#: process ever signs carries in `signer_key_id` -- an operator reading a
#: row should be able to tell at a glance that it was signed by the local,
#: unconfigured key rather than a real custody-backed one.
_LOCAL_SIGNING_KEY_ID = "arc-operational-event-local-1"


class OperationalChainIntegrityError(RegistryError):
    """The chain does not verify, or an append would break it
    (`arc_operational_integrity_failed`, 409).

    Carries `reason_code`: one of `"sequence_gap"`, `"chain_link_violation"`,
    `"changed_predecessor"`, `"signature_invalid"`, `"stale_head"`, or
    `"sequence_contention"`. Never a repair opportunity -- see the module
    docstring's "recovery never silently rewrites history": this exception
    is exactly the shape that rule takes in code, raised rather than
    caught and fixed.
    """

    def __init__(self, message: str, *, reason_code: str) -> None:
        super().__init__(message)
        self.reason_code = reason_code


class OperationalChainIdempotencyConflict(RegistryError):
    """Same idempotency key, a different request (`arc_idempotency_conflict`, 409).

    An exact retry (same key, same event_type/payload) is never rejected --
    see `append_event`'s own docstring for how that is resolved instead.
    """


@dataclasses.dataclass(frozen=True)
class OperationalActor:
    """The `{issuer, subject, role}` triple recorded on every event."""

    issuer: str
    subject: str
    role: str


#: The one actor every genesis event carries. Also legitimate for any other
#: system-authored transition (`freshness_downgraded`) that has no human
#: initiator -- callers reuse this rather than constructing an equivalent
#: value themselves, which is what keeps `actor_issuer`/`actor_subject`
#: from drifting into a second spelling of "the system."
SYSTEM_ACTOR = OperationalActor(issuer=SYSTEM_ACTOR_ISSUER, subject=SYSTEM_ACTOR_SUBJECT, role=ACTOR_ROLE_SYSTEM)


@dataclasses.dataclass(frozen=True)
class AppendResult:
    """What a won append hands back -- deliberately narrow, matching
    `ProposalService`/`ArtifactMaterialisationService`'s own convention of
    returning identity rather than the row a caller can re-read if it needs
    more."""

    event_id: uuid.UUID
    sequence: int
    event_digest: str


def build_event_payload(
    *,
    initial_freshness_basis: str | None = None,
    retention_floor_days: int | None = None,
    legal_hold_active: bool | None = None,
    artifact_semantics_digest: str | None = None,
    hold_id: uuid.UUID | None = None,
    reason_code: str | None = None,
    authority_evidence_digest: str | None = None,
    placed_at: datetime.datetime | None = None,
    released_at: datetime.datetime | None = None,
    prior_deadline: datetime.datetime | None = None,
    later_deadline: datetime.datetime | None = None,
) -> dict[str, Any]:
    """The closed `event_payload` shape, every key present and defaulted to
    `None`.

    `arc_operational_event_v1`'s payload schema requires every one of these
    eleven keys as a *key* -- nullability lives on the value, not on
    whether the key exists at all -- so a caller building this dict by hand
    one field at a time would silently produce a `missing_field` refusal
    for every field it did not think to set. Building it here once means
    every event writer gets the closed shape for free and only ever
    supplies the handful of fields its own event type actually uses.
    """
    return {
        "initial_freshness_basis": initial_freshness_basis,
        "retention_floor_days": retention_floor_days,
        "legal_hold_active": legal_hold_active,
        "artifact_semantics_digest": artifact_semantics_digest,
        "hold_id": str(hold_id) if hold_id is not None else None,
        "reason_code": reason_code,
        "authority_evidence_digest": authority_evidence_digest,
        "placed_at": _rfc3339(placed_at) if placed_at is not None else None,
        "released_at": _rfc3339(released_at) if released_at is not None else None,
        "prior_deadline": _rfc3339(prior_deadline) if prior_deadline is not None else None,
        "later_deadline": _rfc3339(later_deadline) if later_deadline is not None else None,
    }


def _rfc3339(moment: datetime.datetime) -> str:
    """RFC 3339 UTC with a literal `Z` -- the exact shape the profile's
    timestamp pattern requires. `datetime.isoformat()` on its own emits
    `+00:00`, which the pattern deliberately refuses (the fixture suite's
    own "equivalent timezone offset" negative case): this profile has one
    canonical timestamp spelling, not several that compare equal."""
    dt = moment.astimezone(datetime.UTC)
    if dt.microsecond:
        return dt.strftime("%Y-%m-%dT%H:%M:%S.%f") + "Z"
    return dt.strftime("%Y-%m-%dT%H:%M:%S") + "Z"


def _request_digest(*, event_type: str, payload: Mapping[str, Any]) -> str:
    """The service-bookkeeping digest `append_event`'s own idempotency check
    compares -- not part of the closed `arc_operational_event_v1` field set
    (that profile was frozen before this task existed and has no field for
    it), just this module's own record of "what was actually asked for"
    under one idempotency key, the same role `admission_request_payload_
    digest` plays in `source_admission.py`."""
    encoded = json.dumps({"event_type": event_type, "payload": payload}, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Signing. See the module docstring for why this generates its own key
# rather than reaching into `signing.py`.
# ---------------------------------------------------------------------------


@functools.lru_cache(maxsize=1)
def _process_signing_key() -> tuple[str, Ed25519PrivateKey]:
    """This process's operational-event signing keypair, generated exactly
    once and cached for the process's lifetime.

    Cached rather than generated per `OperationalChainService` instance:
    two independent wiring call sites (`wiring/services.py`,
    `wiring/jobs.py` -- see each one's own comment) construct their own
    instance, and both have to sign with the same key for a chain either
    one extends to stay verifiable by the other.
    """
    return _LOCAL_SIGNING_KEY_ID, Ed25519PrivateKey.generate()


#: Every public key this process has ever signed with, by key id -- not
#: only the current one. `verify_chain` looks a stored `signer_key_id` up
#: here rather than assuming it always matches `self._key_id`, because a
#: chain may carry events appended under a key this exact instance did not
#: generate (see the module docstring).
_KEY_REGISTRY: dict[str, Ed25519PublicKey] = {}


def _register_public_key(key_id: str, public_key: Ed25519PublicKey) -> None:
    _KEY_REGISTRY.setdefault(key_id, public_key)


def _verify(public_key: Ed25519PublicKey, digest_hex: str, signature_hex: str) -> bool:
    try:
        public_key.verify(bytes.fromhex(signature_hex), _SIGNATURE_DOMAIN + bytes.fromhex(digest_hex))
    except InvalidSignature:
        return False
    return True


class OperationalChainService:
    """Appends to, and re-verifies, one revision's operational event chain.

    Not yet wired into any read path: `registry.arc.service.integrity`
    (added by a later task, per this task's own non-goals) is where
    mandatory serving, corpus assembly, selection, and protected-action
    authorization will call something that ultimately calls `verify_chain`
    below. This class only has to make that later wiring possible, not
    perform it.
    """

    def __init__(
        self,
        *,
        clock: Clock,
        deployment_id: str,
        key_id: str | None = None,
        private_key: Ed25519PrivateKey | None = None,
    ) -> None:
        if key_id is None or private_key is None:
            cached_key_id, cached_private_key = _process_signing_key()
            key_id = key_id if key_id is not None else cached_key_id
            private_key = private_key if private_key is not None else cached_private_key
        self._clock = clock
        self._deployment_id = deployment_id
        self._key_id = key_id
        self._private_key = private_key
        _register_public_key(key_id, private_key.public_key())

    async def append_event(
        self,
        session: AsyncSession,
        *,
        artifact_id: uuid.UUID,
        revision_id: uuid.UUID,
        event_type: str,
        actor: OperationalActor,
        payload: Mapping[str, Any],
        authorization_decision_reference: str,
        authority_evidence_digest: str,
        idempotency_key: str,
    ) -> AppendResult:
        """Append one event -- genesis or continuation, whichever this
        revision's chain needs next -- and the pending checkpoint outbox
        row that goes with it, all in the caller's own transaction.

        Genesis (`event_type == EVENT_INITIALIZED`) is not a separate
        method: whether this call is genesis or a continuation is decided
        by whether a head row already exists for *revision_id*, locked
        `FOR UPDATE` the same way either way. That lock is what serializes
        concurrent appends to the same chain -- two callers racing to
        extend it block on each other rather than both reading the same
        "next sequence."

        **Idempotency.** `idempotency_key` is hashed and checked against
        `arc_operational_events`'s own `UNIQUE (revision_id,
        idempotency_key_digest)` after the lock is held: an exact retry
        (same key, same `event_type`/`payload`) returns the original
        `AppendResult` without writing a second event; the same key with a
        changed `event_type` or `payload` raises
        `OperationalChainIdempotencyConflict`.
        """
        idempotency_key_digest = hashlib.sha256(idempotency_key.encode("utf-8")).hexdigest()
        request_digest = _request_digest(event_type=event_type, payload=payload)

        # A fast, lock-free check first: correctness never depends on this
        # one succeeding (the locked recheck below is what actually
        # decides), but it means a true retry -- the overwhelmingly common
        # case, since a caller only ever reaches this with a fresh key on
        # a genuinely new transition -- never has to wait on the head lock
        # at all.
        existing = await queries.find_by_idempotency(session, revision_id, idempotency_key_digest)
        if existing is not None:
            return self._resolve_retry(existing, request_digest)

        head = await queries.lock_head(session, revision_id)
        if head is None:
            if event_type != EVENT_INITIALIZED:
                raise OperationalChainIntegrityError(
                    f"revision {revision_id} has no operational chain yet; the first event must be "
                    f"{EVENT_INITIALIZED!r}, not {event_type!r}",
                    reason_code="chain_link_violation",
                )
            sequence = 0
            previous_digest: str | None = None
        else:
            if event_type == EVENT_INITIALIZED:
                raise OperationalChainIntegrityError(
                    f"revision {revision_id} already has an operational chain; refusing a second "
                    f"{EVENT_INITIALIZED!r} event",
                    reason_code="chain_link_violation",
                )
            sequence = head.next_sequence
            previous_digest = head.last_event_digest

        event_id = uuid.uuid4()
        created_at = self._clock.now()
        canonical_obj: dict[str, Any] = {
            "profile": OPERATIONAL_EVENT_PROFILE,
            "event_id": str(event_id),
            "artifact_id": str(artifact_id),
            "revision_id": str(revision_id),
            "sequence": sequence,
            "event_type": event_type,
            "event_payload": dict(payload),
            "actor_issuer": actor.issuer,
            "actor_subject": actor.subject,
            "actor_role": actor.role,
            "authorization_decision_reference": authorization_decision_reference,
            "authority_evidence_digest": authority_evidence_digest,
            "idempotency_key_digest": idempotency_key_digest,
            "previous_event_digest": previous_digest,
            "signer_key_id": self._key_id,
            "created_at": _rfc3339(created_at),
        }
        canonical_bytes = canonicalize_operational_event_v1(canonical_obj)
        digest = hashlib.sha256(canonical_bytes).hexdigest()
        signature = self._private_key.sign(_SIGNATURE_DOMAIN + bytes.fromhex(digest))

        try:
            async with session.begin_nested():
                await queries.insert_event(
                    session,
                    revision_id=revision_id,
                    sequence=sequence,
                    event_id=event_id,
                    artifact_id=artifact_id,
                    event_type=event_type,
                    payload=dict(payload),
                    actor_issuer=actor.issuer,
                    actor_subject=actor.subject,
                    actor_role=actor.role,
                    authorization_decision_reference=authorization_decision_reference,
                    authority_evidence_digest=authority_evidence_digest,
                    idempotency_key_digest=idempotency_key_digest,
                    previous_digest=previous_digest,
                    signer_key_id=self._key_id,
                    digest=digest,
                    signature=signature.hex(),
                    signature_profile=SIGNATURE_PROFILE,
                    request_digest=request_digest,
                    created_at=created_at,
                )
                if head is None:
                    await queries.insert_head(
                        session,
                        revision_id=revision_id,
                        next_sequence=1,
                        last_event_digest=digest,
                        updated_at=created_at,
                    )
                else:
                    advanced = await queries.advance_head(
                        session,
                        revision_id=revision_id,
                        expected_previous=previous_digest,
                        next_sequence=sequence + 1,
                        digest=digest,
                        updated_at=created_at,
                    )
                    if advanced != 1:
                        # Belt and braces against the lock above: if this
                        # ever affects zero rows, something moved the head
                        # between the locked read and here, and continuing
                        # would fork the chain.
                        raise OperationalChainIntegrityError(
                            f"operational event head for revision {revision_id} moved during append at "
                            f"sequence {sequence}",
                            reason_code="stale_head",
                        )
                checkpoint_id = uuid.uuid4()
                await queries.insert_checkpoint(
                    session,
                    checkpoint_id=checkpoint_id,
                    deployment_id=self._deployment_id,
                    revision_id=revision_id,
                    sequence=sequence,
                    event_id=event_id,
                    head_digest=digest,
                    created_at=created_at,
                )
        except IntegrityError:
            # Lost a race for this exact idempotency key or this exact
            # sequence slot. Resolve exactly like a sequential retry would
            # have -- the row that won is now visible to this same
            # transaction, since the failed insert was isolated to its own
            # SAVEPOINT rather than aborting the caller's transaction.
            resolved = await queries.find_by_idempotency(session, revision_id, idempotency_key_digest)
            if resolved is not None:
                return self._resolve_retry(resolved, request_digest)
            raise OperationalChainIntegrityError(
                f"revision {revision_id} sequence {sequence} was claimed by a concurrent append; retry",
                reason_code="sequence_contention",
            ) from None

        return AppendResult(event_id=event_id, sequence=sequence, event_digest=digest)

    def _resolve_retry(self, existing: ExistingEvent, request_digest: str) -> AppendResult:
        if existing.request_payload_digest != request_digest:
            raise OperationalChainIdempotencyConflict(
                f"revision {existing.revision_id} idempotency key already identifies a different " "operational event"
            )
        return AppendResult(event_id=existing.event_id, sequence=existing.sequence, event_digest=existing.event_digest)

    async def verify_chain(self, session: AsyncSession, revision_id: uuid.UUID) -> None:
        """Re-derive every event digest and signature and confirm the
        chain reaches its head. Raises `OperationalChainIntegrityError` on
        the first gap, broken link, tampered payload, invalid signature, or
        head that does not match the end of the chain.

        Deliberately O(n) in the chain's own length and deliberately not on
        the append path -- appending trusts the locked head alone (the same
        design `ReceiptService` uses); this is the auditor's operation, run
        when a chain's integrity is in question rather than on every write.
        Read-path wiring (mandatory serving, selection, ...) calling this
        on every request is a later task's job, not this method's.
        """
        rows = await queries.load_events(session, revision_id)
        if not rows:
            raise OperationalChainIntegrityError(
                f"revision {revision_id} has no operational events", reason_code="sequence_gap"
            )

        previous: str | None = None
        for expected_sequence, row in enumerate(rows):
            if row.sequence != expected_sequence:
                raise OperationalChainIntegrityError(
                    f"revision {revision_id} operational chain has a gap: expected sequence "
                    f"{expected_sequence}, found {row.sequence}",
                    reason_code="sequence_gap",
                )
            if row.previous_event_digest != previous:
                raise OperationalChainIntegrityError(
                    f"revision {revision_id} operational event at sequence {row.sequence} does not link to "
                    "its predecessor",
                    reason_code="changed_predecessor",
                )

            canonical_obj: dict[str, Any] = {
                "profile": OPERATIONAL_EVENT_PROFILE,
                "event_id": str(row.event_id),
                "artifact_id": str(row.artifact_id),
                "revision_id": str(revision_id),
                "sequence": row.sequence,
                "event_type": row.event_type,
                "event_payload": row.event_payload,
                "actor_issuer": row.actor_issuer,
                "actor_subject": row.actor_subject,
                "actor_role": row.actor_role,
                "authorization_decision_reference": row.authorization_decision_reference,
                "authority_evidence_digest": row.authority_evidence_digest,
                "idempotency_key_digest": row.idempotency_key_digest,
                "previous_event_digest": row.previous_event_digest,
                "signer_key_id": row.signer_key_id,
                "created_at": _rfc3339(row.created_at),
            }
            recomputed = hashlib.sha256(canonicalize_operational_event_v1(canonical_obj)).hexdigest()
            if recomputed != row.event_digest:
                raise OperationalChainIntegrityError(
                    f"revision {revision_id} operational event at sequence {row.sequence} has a tampered " "payload",
                    reason_code="changed_predecessor",
                )

            public_key = _KEY_REGISTRY.get(row.signer_key_id)
            if public_key is None or not _verify(public_key, row.event_digest, row.signature):
                raise OperationalChainIntegrityError(
                    f"revision {revision_id} operational event at sequence {row.sequence} has an invalid " "signature",
                    reason_code="signature_invalid",
                )
            previous = row.event_digest

        head = await queries.load_head(session, revision_id)
        if head is None:
            raise OperationalChainIntegrityError(
                f"revision {revision_id} has operational events but no head", reason_code="stale_head"
            )
        if head.last_event_digest != previous or head.next_sequence != len(rows):
            raise OperationalChainIntegrityError(
                f"revision {revision_id} operational event head does not match the end of its chain",
                reason_code="stale_head",
            )


__all__ = [
    "ACTOR_ROLE_HUMAN",
    "ACTOR_ROLE_SYSTEM",
    "EVENT_FRESHNESS_DOWNGRADED",
    "EVENT_INITIALIZED",
    "EVENT_LEGAL_HOLD_PLACED",
    "EVENT_LEGAL_HOLD_RELEASED",
    "EVENT_RETENTION_EXTENDED",
    "SIGNATURE_PROFILE",
    "SYSTEM_ACTOR",
    "SYSTEM_ACTOR_ISSUER",
    "SYSTEM_ACTOR_SUBJECT",
    "AppendResult",
    "OperationalActor",
    "OperationalChainIdempotencyConflict",
    "OperationalChainIntegrityError",
    "OperationalChainService",
    "build_event_payload",
]
