"""MCP preflight: the identity handshake ARC tools require before they run.

REST re-authenticates on every request. A long-lived MCP connection does
not -- it authenticates once and then serves many tool calls -- so without
something here, a credential that changes mid-connection would keep working
until the connection dropped. That is the gap this module closes: an ARC
tool refuses to run until the connection has completed a `whoami` preflight,
and refuses again the moment the identity behind that preflight stops
matching.

Three decisions carry the security of this:

**The record is keyed by a server-assigned connection ID, never by anything
the caller sends.** A caller-supplied session string is a session string the
caller can guess, and guessing another connection's key would mean adopting
its preflight.

**The comparison is against a fingerprint, not a claim of sameness.** Each
tool call recomputes the credential fingerprint and compares; a token
swapped for another with the same subject still changes the fingerprint,
because the fingerprint covers the token itself and not just who it says
you are.

**Anything unexpected invalidates.** Changed credential, changed tenant
selector, changed restrictions, expired authentication, unknown connection
-- all refuse. There is no branch that falls through to "probably fine".
"""

from __future__ import annotations

import dataclasses
import datetime
import hashlib
import hmac
import secrets
import uuid

# The bounded code every refusal returns. One code, because which check
# failed is not the caller's business -- the remedy is the same: call
# `whoami` again on a valid credential.
PREFLIGHT_REQUIRED = "mcp_preflight_required"


class PreflightError(Exception):
    """The connection has no usable preflight. Always refuse, never degrade."""

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.code = PREFLIGHT_REQUIRED
        self.reason = reason


def new_connection_id() -> str:
    """An unguessable identifier for one live MCP connection.

    Generated by the server, handed to nothing, and used only as a local
    map key. `token_urlsafe` rather than a UUID because a UUID4 printed in
    a log looks like a resource identifier somebody might try to use.
    """
    return secrets.token_urlsafe(32)


def credential_fingerprint(raw_token: str) -> str:
    """A digest of the credential itself, not of who it claims to be.

    Two tokens for the same subject fingerprint differently, which is the
    point: a re-issued or swapped token is a new authentication and must
    re-preflight, even though every claim in it may be identical.
    """
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


def restriction_digest(restrictions: object) -> str:
    """A stable digest over whatever restrictions the credential carries.

    Sorted and stringified so an unordered set of scopes cannot appear to
    change merely because it serialized differently.
    """
    if restrictions is None:
        return hashlib.sha256(b"").hexdigest()
    if isinstance(restrictions, dict):
        material = "|".join(f"{k}={restrictions[k]}" for k in sorted(restrictions))
    elif isinstance(restrictions, list | tuple | set | frozenset):
        material = "|".join(sorted(str(r) for r in restrictions))
    else:
        material = str(restrictions)
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


@dataclasses.dataclass(frozen=True)
class PreflightRecord:
    """What a completed `whoami` recorded about one connection."""

    connection_id: str
    credential_fingerprint: str
    tenant_id: uuid.UUID
    actor_id: uuid.UUID
    oidc_issuer: str
    oidc_subject: str
    roles: tuple[str, ...]
    token_restriction_digest: str
    authentication_expires_at: datetime.datetime
    completed_at: datetime.datetime


class PreflightRegistry:
    """In-memory preflight state, one record per live connection.

    In-memory on purpose. The state describes a connection this process is
    holding open, so it cannot outlive the process that holds it -- a
    restart drops every connection, and a record that survived into the new
    process would be a preflight for a connection nobody is on the other
    end of.
    """

    def __init__(self) -> None:
        self._records: dict[str, PreflightRecord] = {}

    def record(
        self,
        *,
        connection_id: str,
        credential_fingerprint: str,
        tenant_id: uuid.UUID,
        actor_id: uuid.UUID,
        oidc_issuer: str,
        oidc_subject: str,
        roles: tuple[str, ...],
        token_restriction_digest: str,
        authentication_expires_at: datetime.datetime,
        completed_at: datetime.datetime,
    ) -> PreflightRecord:
        """Complete the preflight for `connection_id`, replacing any prior one.

        Replacing rather than rejecting a second `whoami`: a client
        legitimately re-preflights after refreshing its token, and the new
        record is simply the current truth.
        """
        entry = PreflightRecord(
            connection_id=connection_id,
            credential_fingerprint=credential_fingerprint,
            tenant_id=tenant_id,
            actor_id=actor_id,
            oidc_issuer=oidc_issuer,
            oidc_subject=oidc_subject,
            roles=roles,
            token_restriction_digest=token_restriction_digest,
            authentication_expires_at=authentication_expires_at,
            completed_at=completed_at,
        )
        self._records[connection_id] = entry
        return entry

    def require(
        self,
        *,
        connection_id: str | None,
        credential_fingerprint: str,
        tenant_id: uuid.UUID,
        token_restriction_digest: str,
        now: datetime.datetime,
    ) -> PreflightRecord:
        """Return the record, or refuse. Called before any ARC service runs.

        Ordering matters: this is the first thing an ARC tool does, so a
        caller that never preflighted cannot reach a service to probe it
        for the existence of a receipt or an artifact.
        """
        if not connection_id:
            msg = "no server connection identity is associated with this call"
            raise PreflightError(msg)

        entry = self._records.get(connection_id)
        if entry is None:
            msg = "this connection has not completed the required whoami preflight"
            raise PreflightError(msg)

        if entry.authentication_expires_at <= now:
            # Drop it: the record can never become valid again, and leaving
            # it would let a later clock skew resurrect it.
            self.invalidate(connection_id)
            msg = "the authentication behind this connection's preflight has expired"
            raise PreflightError(msg)

        # Constant-time on the fingerprints. They are digests rather than
        # secrets, but an early-exit comparison here leaks how much of a
        # forged fingerprint was correct, and the comparison is cheap.
        if not hmac.compare_digest(entry.credential_fingerprint, credential_fingerprint):
            self.invalidate(connection_id)
            msg = "the credential on this connection has changed since preflight"
            raise PreflightError(msg)

        if entry.tenant_id != tenant_id:
            self.invalidate(connection_id)
            msg = "the tenant selection on this connection has changed since preflight"
            raise PreflightError(msg)

        if not hmac.compare_digest(entry.token_restriction_digest, token_restriction_digest):
            self.invalidate(connection_id)
            msg = "the token restrictions on this connection have changed since preflight"
            raise PreflightError(msg)

        return entry

    def invalidate(self, connection_id: str) -> None:
        """Forget one connection's preflight. Idempotent.

        Called on disconnect, logout, and by `require` whenever it refuses:
        a record that just failed a check must not survive to be checked
        again, because the next call would otherwise re-run the same
        comparison against state already known to be stale.
        """
        self._records.pop(connection_id, None)

    def clear(self) -> None:
        """Drop everything. For shutdown and tests."""
        self._records.clear()

    def __len__(self) -> int:
        return len(self._records)


__all__ = [
    "PREFLIGHT_REQUIRED",
    "PreflightError",
    "PreflightRecord",
    "PreflightRegistry",
    "credential_fingerprint",
    "new_connection_id",
    "restriction_digest",
]
